In [2]:
import numpy as np
print(44)

44


In [16]:
b = np.arange(11,11+16 )
b.reshape( 4,-1)

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22],
       [23, 24, 25, 26]])

In [18]:
np.hsplit(b,4)

[array([11, 12, 13, 14]),
 array([15, 16, 17, 18]),
 array([19, 20, 21, 22]),
 array([23, 24, 25, 26])]

In [21]:
c=np.arange(0,30)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [22]:
d=np.arange(0,20,5)
d

array([ 0,  5, 10, 15])

In [23]:
c[d]

array([ 0,  5, 10, 15])

In [30]:
c.reshape(10,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [39]:
k=np.arange(100,200)
k=k.reshape(10,-1)
k

array([[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169],
       [170, 171, 172, 173, 174, 175, 176, 177, 178, 179],
       [180, 181, 182, 183, 184, 185, 186, 187, 188, 189],
       [190, 191, 192, 193, 194, 195, 196, 197, 198, 199]])

In [41]:
k[2,:]

array([120, 121, 122, 123, 124, 125, 126, 127, 128, 129])

In [43]:
k[:,3]

array([103, 113, 123, 133, 143, 153, 163, 173, 183, 193])

In [48]:
base_data=np.floor((np.random.random((5,5))-.5)*100)
base_data

array([[ 15.,  40., -38., -29., -16.],
       [-27., -47., -37.,  39.,  33.],
       [-42.,  36.,  31.,  43.,  40.],
       [-28.,  29.,  22.,  36.,  12.],
       [-26.,   4., -17.,   1.,  11.]])

In [47]:
np.cos(base_data)

array([[-0.64134753, -0.16382974, -0.99937716, -0.86740818,  0.99374498],
       [-0.83530308,  0.39404737, -0.98525853, -0.99249542, -0.99983267],
       [ 0.61884519,  0.99774956, -0.15649104,  0.75265723,  0.98113387],
       [-0.37722665,  0.86114704, -0.06919704,  0.18072099,  0.94409422],
       [ 0.97844226,  0.78353086,  0.2996446 , -0.86656006, -0.86305901]])